package org.binaryitplanet.tradinget.Utils

import java.io.Serializable

data class InvoiceUtils(
    var ledgerId: String?,
    var invoiceNo: String?,
    var invoiceDate: String?,
    var terms: String?,
    var placeOfSupply: String?,
    var shippingBillNo: String?,
    var shippingDate: String?,
    var transporterName: String?,
    var lrRRNo: String?,
    var eCommerceParty: String?,
    var eCommercePartyDate: String?,
    var sellerName: String?,
    var sellerAddress1: String?,
    var sellerAddress2: String?,
    var sellerAddress3: String?,
    var sellerAddress4: String?,
    var sellerStateCode: String?,
    var sellerPan: String?,
    var sellerGSTIN: String?,
    var buyerName: String?,
    var buyerAddress1: String?,
    var buyerAddress2: String?,
    var buyerAddress3: String?,
    var buyerAddress4: String?,
    var buyerStateCode: String?,
    var buyerPan: String?,
    var buyerGSTIN: String?,
    var taxIsPayableOnReverseCharge: String?,
    var hsnSACCode: String?,
    var cgstRate: String?,
    var cgstAmount: String,
    var sgstRate: String?,
    var sgstAmount: String?,
    var igstRate: String?,
    var igstAmount: String?,
    var roundingDifference: String?,
    var netBillAmount: String?,
    var totalAmount: String?,
    var amountInWord: String?,
    var finalAmount: String?,
    var totalQuality: String,
    var bankNameAndBrunch: String?,
    var currentAccount: String?,
    var ifsc: String?,
    var imageUrl: String?
): Serializable {
}